name: Pull Request Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test-project:
    needs: deploy-action-code
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=macOS
          - platform=iOS Simulator,OS=latest,name=iPhone 11
          - platform=iOS Simulator,OS=latest,name=iPad Pro (9.7-inch)
          - platform=tvOS Simulator,OS=latest,name=Apple TV 4K
        action: [ build, test ]
        use-xcpretty: [ true, false ]
        include:
          - destination: platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 44mm
            action: build
            use-xcpretty: true
          - destination: platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 44mm
            action: build
            use-xcpretty: false
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      - name: Install dependencies
        run: sudo npm i -g @zeit/ncc typescript
      - uses: actions/checkout@v2
      - name: Generate action code
        run: npm run deploy
      - uses: './'
        with:
          project: __test__/TestProject/TestProject.xcodeproj
          scheme: TestProject
          destination: ${{matrix.destination}}
          action: ${{matrix.action}}
          use-xcpretty: ${{matrix.use-xcpretty}}
      - name: Check for derived data
        run: ls ~/Library/Developer/Xcode/DerivedData/ | grep -q '^TestProject.*'

  test-workspace:
    needs: deploy-action-code
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=macOS
          - platform=iOS Simulator,OS=latest,name=iPhone 11
          - platform=iOS Simulator,OS=latest,name=iPad Pro (9.7-inch)
          - platform=tvOS Simulator,OS=latest,name=Apple TV 4K
        action: [ build, test ]
        use-xcpretty: [ true, false ]
        include:
          - destination: platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 44mm
            action: build
            use-xcpretty: true
          - destination: platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 44mm
            action: build
            use-xcpretty: false
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      - name: Install dependencies
        run: sudo npm i -g @zeit/ncc typescript
      - uses: actions/checkout@v2
      - name: Generate action code
        run: npm run deploy
      - uses: './'
        with:
          workspace: __test__/TestProject/TestProject.xcworkspace
          scheme: TestProject
          destination: ${{matrix.destination}}
          action: ${{matrix.action}}
          use-xcpretty: ${{matrix.use-xcpretty}}
      - name: Check for derived data
        run: ls ~/Library/Developer/Xcode/DerivedData/ | grep -q '^TestProject.*'
